### ISSUE TITLE
MRI support

### ISSUE THREAD

**Issue by lypanov** [yokolet/clementine#1]
hey, i was wondering if you were interested in merging in my fork https://github.com/lypanov/clementine ?

it adds support for MRI and nail gun. this provides sub second compiles without the jruby dependency.

**Comment by yokolet** [comment]
That's what I'm thinking. :)

Intentionally, I supported JRuby only for the first impl because I'm a JRuby committer. But, if I think of users, MRI support is very important and not so difficult. So, I'm thinking of that and want to make it before the release.

Did you confirm MRI support is working? I'll check it out though.

**Comment by lypanov** [comment]
all works for me yes.

i also updated the goog.jar to add third party directory as we're using goog.dom.query.

just now pushed a new version which adds dep support so you can have a bla.cljs and a blahdep.cljs in the same asset dir and have (after config) dev mode Just Work.

we're not able to deploy jruby alas so i've been unable to test that.

**Comment by lypanov** [comment]
btw, without nail gun compiles take 4 seconds or so so i think it only really makes sense to support a configuration of either jruby, or MRI with nail gun. there is a nailgun gem which works well, but its extremely rough at the edges.

**Comment by lypanov** [comment]
my code is filled with gunk btw and i apologize for that. i have a project deadline alas and wanted to move fast rather than carefully :)

**Comment by evjan** [comment]
Was this ever done? Is there anything I can do to help?

**Comment by yokolet** [comment]
@evjan this should be closed. I confirmed clementine worked on MRI. Thanks for reminding me this.
